name: XXX Level 1 - Smoke Tests

on:
  push:
    branches: [ "main"]

permissions:
  contents: read
  pull-requests: read

jobs:
  setup-wf-inputs:
    uses: ./.github/workflows/rwf-setup-inputs.yml
    with:
      block: siag
      block-suffix: _SMOKE
      testsuite: sanity
      runner-name: ubuntu-latest
  clone:
    needs: setup-wf-inputs
    runs-on: ${{ needs.setup-wf-inputs.outputs.runner-name }}
    env:
      GHA_CHECKOUT_DIR : ${{ needs.setup-wf-inputs.outputs.checkout-path }}
      GHA_BLOCK : ${{ needs.setup-wf-inputs.outputs.block-name }}
    outputs:
      changes_flag: ${{ steps.filter.outputs.changes_flag }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        path : ${{ env.GHA_CHECKOUT_DIR }}
    - name: Filter Changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        working-directory: ${{ env.GHA_CHECKOUT_DIR }}
        filters: |
          changes_flag:
            - '${{env.GHA_BLOCK}}/**'
    - name: Show Repository
      run: |
        cd $GITHUB_WORKSPACE/$GHA_CHECKOUT_DIR
        pwd
        git show --no-patch
  run-rwf-job1:
    runs-on:  ${{ needs.setup-wf-inputs.outputs.runner-name }}
    needs: [setup-wf-inputs, clone]
    steps:
    - name: Echo Inputs
      run: |
        echo ${{ needs.setup-wf-inputs.outputs.block-name }}
        echo ${{ needs.setup-wf-inputs.outputs.testsuite-name }}
        echo ${{ needs.setup-wf-inputs.outputs.checkout-root-dir }}
        echo ${{ needs.setup-wf-inputs.outputs.checkout-path }}
        echo ${{ needs.setup-wf-inputs.outputs.runner-name }}
    - name: Test Checkout Directory
      run: |
        cd $GITHUB_WORKSPACE/${{ needs.setup-wf-inputs.outputs.checkout-path }}
        pwd        
  run-rwf-job2:
    needs: [setup-wf-inputs, clone]
    # if: ${{ needs.clone.outputs.changes_flag == 'true' }}
    strategy:
      matrix:
        tests: [case1_test, case2_test, case3_test]
    uses: ./.github/workflows/rwf-wf-1.yml
    with:
        checkout-path: ${{ needs.setup-wf-inputs.outputs.checkout-path }}
        block: ${{ needs.setup-wf-inputs.outputs.block-name }}
        testsuite: ${{ needs.setup-wf-inputs.outputs.testsuite-name }}
        testname: ${{ matrix.tests }}
        runner-name: ${{ needs.setup-wf-inputs.outputs.runner-name }}
      
