name: Generate Input Strings for Re-usable Workflows

on:
  workflow_call:
    inputs:
      block:
        required: true
        type: string
      testsuite:
        required: true
        type: string
      testnames:
        required: true
        type: string
      block-suffix:
        type: string
        default: ''
      block-prefix:
        type: string
        default: ''
      runner-name:
        required: true
        type: string
        default: ubuntu-latest
    outputs:
      checkout-root-dir:
        description: "Check Root Director"
        value: ${{ jobs.prep-wf-inputs.outputs.checkout-root-dir }}
      checkout-path:
        description: "Check Root Director"
        value: ${{ jobs.prep-wf-inputs.outputs.checkout-path }}        
      block-name:
        description: "Block Name"
        value: ${{ jobs.prep-wf-inputs.outputs.block-name }}
      test-names:
        description: "Testsuite Names"
        value: ${{ jobs.prep-wf-inputs.outputs.test-names }}
      testsuite-name:
        description: "Testsuite Name"
        value: ${{ jobs.prep-wf-inputs.outputs.testsuite-name }}
      runner-name:
        description: "Runner Name"
        value: ${{ jobs.prep-wf-inputs.outputs.runner-name }}
jobs:
  prep-wf-inputs:
    name: Generate RWF Inputs
    runs-on: "${{ inputs.runner-name }}" 
    outputs:
      checkout-root-dir: ${{ steps.checkout-root-dir.outputs.uppercase }}
      checkout-path: ${{ steps.checkout-path.outputs.path }}  
      block-name: ${{ inputs.block }}
      testsuite-name : ${{ inputs.testsuite }}
      test-names : ${{ inputs.testnames }}
      runner-name: ${{ inputs.runner-name }}
    steps:
      - name : set checkout-root-dir
        id: checkout-root-dir
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ inputs.block-prefix }}${{ inputs.block }}${{ inputs.block-suffix }}
      - name: set checkout-path
        id: checkout-path
        run: echo "path=${{ steps.checkout-root-dir.outputs.uppercase }}/${{ github.actor }}/${{ github.event_name }}/${{ github.run_number }}" >> $GITHUB_OUTPUT
